### ISSUE TITLE
project list throws server error

### ISSUE THREAD

**Issue by rasos** [kainbacher/Notethrower#11]
See http://oneloudr.com/OL/projectList.php

**Comment by hjonas** [comment]
this url is incorrect, use either

http://oneloudr.com/OL/projectList

or 

http://oneloudr.com/OL/Site/projectList.php

**Comment by rasos** [comment]
ok, sorry I did not mention where it happened, I think you need to change the link on the bottom of a release page:
http://oneloudr.com/OL/project?action=edit&pid=338

**Comment by hjonas** [comment]
this is fixed now. futhermore i don't display the link for non-logged-in
users because it only leads to a "please login" page in such a case.
