### ISSUE TITLE
test issue

### ISSUE THREAD

**Issue by kainbacher** [kainbacher/Notethrower#2]
test problem, farbe bei der suche ist nicht korrekt

**Comment by hjonas** [comment]
test reply by hanno 

-----Original Message-----
From: kainbacher
[mailto:reply+i-868703-d783bc207465f071ac525daa7080dd890f1251b5@reply.github
.com] 
Sent: Montag, 09. Mai 2011 14:32
To: hanno.jonas@gmail.com
Subject: [Notethrower] test issue (#2)

test problem, farbe bei der suche ist nicht korrekt

## 

Reply to this email directly or view it on GitHub:
https://github.com/kainbacher/Notethrower/issues/2

**Comment by kainbacher** [comment]
:) schön ich hab da grad was schönes für den chrome gefunden: http://githubissues.heroku.com/ gibts also chrome app ... oder geht läuft vielleicht in den anderen auch
