### ISSUE TITLE
createUser.php - Felder ausblenden

### ISSUE THREAD

**Issue by kainbacher** [kainbacher/Notethrower#3]
Hier solle man noch die Felder

"Webpage URL:"
"Paypal account:"
"Artist/Band information:" 
"Additional information:" ausblenden.

nur die Pflichtfelder sollen bleiben.

**Comment by hjonas** [comment]
hi,

createUser.php wird durch account.php ersetzt. ich hab das vor einiger zeit
schon vorbereitet und in die _newurls.txt datei eingetragen.

das account.php dient zum anlegen neuer user aber auch zum editieren des
eigenen profils. soll ich die felder, die du unten aufgelistet hast, nur
beim erstellen neuer accounts ausblenden und beim editieren des profils
anzeigen (so dass man sie nachträglich befüllen kann, wenn man will) oder
gehören die felder generell weg?

lgh

-----Original Message-----
From: kainbacher
[mailto:reply+i-1005695-0b3eb82d0fe58460313941f682323d32394d1370@reply.githu
b.com] 
Sent: Sonntag, 05. Juni 2011 19:26
To: hanno.jonas@gmail.com
Subject: [Notethrower] createUser.php - Felder ausblenden (#3)

Hier solle man noch die Felder

"Webpage URL:"
"Paypal account:"
"Artist/Band information:" 
"Additional information:" ausblenden.

nur die Pflichtfelder sollen bleiben.

## 

Reply to this email directly or view it on GitHub:
https://github.com/kainbacher/Notethrower/issues/3
