### ISSUE TITLE
createUser.php

### ISSUE THREAD

**Issue by kainbacher** [kainbacher/Notethrower#4]
wenn man eingeloggt ist wird bei "Password verification:" statt dem info icon der helptext angezeigt

**Comment by hjonas** [comment]
auch hier gilt: das createUser.php wurde durch das account.php ersetzt. ich
werde das dann entfernen, wenn ich es nicht mehr zum nachschauen brauche.

lgh 

-----Original Message-----
From: kainbacher
[mailto:reply+i-1005741-282a15121df6f9ea4bc1d0a9a49e6c977181b3e7@reply.githu
b.com] 
Sent: Sonntag, 05. Juni 2011 19:42
To: hanno.jonas@gmail.com
Subject: [Notethrower] createUser.php (#4)

wenn man eingeloggt ist wird bei "Password verification:" statt dem info
icon der helptext angezeigt

## 

Reply to this email directly or view it on GitHub:
https://github.com/kainbacher/Notethrower/issues/4
