### ISSUE TITLE
track.php - trackList

### ISSUE THREAD

**Issue by kainbacher** [kainbacher/Notethrower#5]
hier fehlen noch die header daten - also die css und script dateien

**Comment by hjonas** [comment]
das track.php wird durch das trackNew.php ersetzt, wo dann das neue template
system drin ist. diese sachen kannst dann selbst in den templates umstellen.
ich bin aber leider noch nicht so weit. heute werd ich da aber gas geben.

lgh

-----Original Message-----
From: kainbacher
[mailto:reply+i-1005756-fde5581dd52700eb47fc8538e33d288bc54d2456@reply.githu
b.com] 
Sent: Sonntag, 05. Juni 2011 19:51
To: hanno.jonas@gmail.com
Subject: [Notethrower] track.php (#5)

hier fehlen noch die header daten - also die css und script dateien

## 

Reply to this email directly or view it on GitHub:
https://github.com/kainbacher/Notethrower/issues/5
